Repository jung-dam-diary/team-angelbaby-jungdam-fe, pull requests merged in 2021-12, with the labels that each got.

#24 [feat #20]
  src/components/base/Image/index.jsx
  src/components/base/index.jsx
  src/stories/components/Image.stories.jsx
Labels: Component

#29 [feat #23] Icon 컴포넌트 구현
  .eslintrc.json
  package.json
  src/components/base/Icon/index.jsx
  src/components/base/index.jsx
  src/stories/components/Icon.stories.js
  yarn.lock
Labels: Component

#30 [refactor #20]
  src/components/base/Image/index.jsx
  src/stories/components/Image.stories.jsx
Labels: Refactoring

#33 [feat #21]
  src/components/base/Spinner/index.jsx
  src/components/base/index.jsx
  src/stories/components/Spinner.stories.jsx
Labels: Component

#34 [feat #18]
  src/assets/colors/Color.jsx
  src/assets/fonts/Font.jsx
  src/components/base/Button/index.jsx
  src/components/base/index.jsx
  src/stories/components/Button.stories.jsx
Labels: Component

#37 [feat #28]
  src/components/base/Skeleton/Base.jsx
  src/components/base/Skeleton/Box.jsx
  src/components/base/Skeleton/Circle.jsx
  src/components/base/Skeleton/Line.jsx
  src/components/base/Skeleton/index.jsx
  src/components/base/index.jsx
  src/stories/components/Skeleton.stories.jsx
Labels: Component

#31 [feat #19]
  src/components/base/Avatar/index.jsx
  src/components/base/index.jsx
  src/stories/components/Avatar.stories.jsx
Labels: Component

#35 [feat #32]
  src/components/base/Modal/index.jsx
  src/components/base/index.jsx
  src/hooks/index.jsx
  src/hooks/useClickAway.jsx
  src/stories/components/Modal.stories.jsx
Labels: Component

#41 [feat #36]
  src/components/base/Input/index.jsx
  src/components/base/index.jsx
  src/stories/components/Input.stories.jsx
Labels: Component

#59 Feature/#39
  .github/workflows/react.yml
Labels: CICD

#63 [feat #62]
  src/components/base/Button/index.jsx
  src/styles/ResetStyle.jsx
Labels: Bug

#67 [feat #66]
  src/stories/components/Divider.stories.jsx
  src/stories/components/Image.stories.jsx
  src/stories/components/Spinner.stories.jsx
Labels: Bug

#74 [feature #50, #70]
  package.json
  src/assets/lottie/family.json
  src/assets/lottie/laugh.json
  src/assets/lottie/notepad.json
  src/components/base/Button/index.jsx
  src/components/base/Lottie/index.jsx
  src/components/base/index.jsx
  src/components/domain/LandingSwiper/index.jsx
  src/components/domain/index.jsx
  src/pages/LandingPage/index.jsx
  src/pages/index.jsx
  yarn.lock
Labels: Component, Chore, Feature

#69 [feat #68]
  src/assets/Image/defaultUser.png
  src/components/base/Avatar/index.jsx
Labels: Bug

#73 [feat #65]
  src/components/domain/Header/index.jsx
  src/components/domain/index.jsx
  src/pages/MainPage.jsx
Labels: Component

#83 [feat #48]
  .gitignore
  craco.config.js
  package.json
  src/common/api/api.jsx
  src/common/api/memberApi.jsx
  src/common/utils/constants.jsx
  src/components/base/index.jsx
  src/pages/LandingPage/index.jsx
  src/pages/LoginPage/index.jsx
  src/pages/OAuthRedirect/index.jsx
  src/pages/index.jsx
  src/redux/member/index.jsx
  src/redux/store.jsx
  src/redux/user/index.jsx
  src/router/AuthRoute.jsx
  src/router/PreventedRoute.jsx
  src/router/Router.jsx
  src/router/index.jsx
  yarn.lock
Labels: Chore, Feature

#91 [feat #89]
  src/pages/AlbumSettingsPage/index.jsx
  src/pages/index.jsx
Labels: Feature

#96 [feat #80] 일기 생성 페이지 구현
  src/components/base/ProgressBar/index.jsx
  src/components/base/Textarea/index.jsx
  src/components/domain/DiaryCreateStepOne/index.jsx
  src/components/domain/DiaryCreateStepThree/index.jsx
  src/components/domain/DiaryCreateStepTwo/index.jsx
  src/components/domain/Header/index.jsx
  src/components/domain/index.jsx
  src/pages/DiaryCreatePage/index.jsx
  src/pages/DiaryPage/index.jsx
  src/pages/index.jsx
  src/router/Router.jsx
  src/styles/DefaultContainer.jsx
  src/styles/DefaultTemplate.jsx
  src/styles/ResetStyle.jsx
Labels: Feature

#90 [feat #77]
  src/assets/Image/Family.svg
  src/components/base/Image/index.jsx
  src/components/base/index.jsx
  src/components/domain/AlbumInviteList/AlbumInviteCard.jsx
  src/components/domain/AlbumInviteList/index.jsx
  src/components/domain/AlbumSwiper/index.jsx
  src/components/domain/index.jsx
  src/pages/AlbumListPage/index.jsx
  src/pages/index.jsx
  src/redux/albums/index.jsx
Labels: Component, Feature

#97 [feat #78]
  src/components/domain/Header/index.jsx
  src/hooks/index.jsx
  src/hooks/useAuth.jsx
  src/pages/AlbumCreatePage/AlbumCreateStep1.jsx
  src/pages/AlbumCreatePage/AlbumCreateStep2.jsx
  src/pages/AlbumCreatePage/AlbumCreateStep3.jsx
  src/pages/AlbumCreatePage/index.jsx
  src/pages/OAuthRedirect/index.jsx
  src/pages/index.jsx
  src/redux/member/index.jsx
  src/router/AuthRoute.jsx
  src/router/PreventedRoute.jsx
Labels: Component, Feature, Refactoring

#92 [feat #82]
  src/pages/MemberListPage/index.jsx
  src/pages/index.jsx
Labels: Feature

#94 [feat #93]
  src/pages/AlbumSettingsEditPage/index.jsx
  src/pages/index.jsx
Labels: Feature

#102 [feat #95]
  src/components/base/Modal/index.jsx
  src/hooks/index.jsx
  src/hooks/useForm.jsx
  src/pages/MemberInvitePage/index.jsx
  src/pages/index.jsx
Labels: Feature

#105 [feat #104]
  src/pages/AlbumSettingsPage/index.jsx
Labels: Refactoring

#112 [feat #111]
  src/pages/AlbumSettingsEditPage/index.jsx
  src/pages/AlbumSettingsPage/index.jsx
Labels: Bug

#119 [feat #114]
  src/pages/TestPage/index.jsx
  src/router/Router.jsx
Labels: Component

#118 [feat #115]
  src/components/domain/Header/index.jsx
  src/pages/StoryBookDetailPage/index.jsx
  src/pages/StoryBookPage/index.jsx
  src/pages/index.jsx
  src/router/Router.jsx
Labels: Component, Feature

#124 [feat #123]
  package.json
  src/common/api/api.jsx
Labels: Bug

#121 [feat #116]
  src/pages/MemberListPage/index.jsx
  src/router/Router.jsx
Labels: Feature

#128 [feat #122]
  src/pages/SpecialMomentPage/index.jsx
  src/pages/index.jsx
  src/router/Router.jsx
Labels: Feature

#134 [feat #101]
  src/assets/lottie/404.json
  src/pages/Error404Page/index.jsx
  src/pages/index.jsx
  src/router/Router.jsx
Labels: Component, Feature

#133 [feat #131]
  src/common/api/memberApi.jsx
  src/components/domain/Profile/index.jsx
  src/components/domain/ProfileList/ProfileItem.jsx
  src/components/domain/ProfileList/index.jsx
  src/components/domain/index.jsx
  src/pages/ProfilePage/index.jsx
  src/pages/index.jsx
  src/redux/member/index.jsx
  src/router/AuthRoute.jsx
  src/router/Router.jsx
Labels: Component, Feature

#142 [feat #136]
  src/common/api/albumApi.jsx
  src/components/domain/AlbumInviteList/AlbumInviteCard.jsx
  src/components/domain/AlbumInviteList/index.jsx
  src/components/domain/AlbumSwiper/index.jsx
  src/components/domain/Header/index.jsx
  src/pages/AlbumListPage/index.jsx
  src/redux/album/index.jsx
  src/redux/albums/index.jsx
  src/redux/store.jsx
Labels: Feature

#146 [feat #145]
  src/common/api/albumApi.jsx
  src/components/domain/AlbumSwiper/index.jsx
  src/hooks/index.jsx
  src/hooks/useAlbumValidation.jsx
  src/pages/AlbumListPage/index.jsx
  src/router/AlbumValidationRoute.jsx
  src/router/Router.jsx
  src/router/index.jsx
Labels: Feature

#154 [feat #139] 일기 상세 페이지 Api 데이터 통신 구현
  src/common/api/deleteDiaryComment.jsx
  src/common/api/getDiaryComments.jsx
  src/common/api/getDiaryContents.jsx
  src/common/api/postDiaryComment.jsx
  src/common/api/putBookmark.jsx
  src/common/utils/replaceTildeWithDate.jsx
  src/components/domain/DiaryComment/index.jsx
  src/components/domain/DiaryCommentInputForm/index.jsx
  src/components/domain/DiaryContent/index.jsx
  src/components/domain/DiaryHeaderInfo/index.jsx
  src/components/domain/DiaryImages/index.jsx
  src/hooks/usePromise.jsx
  src/pages/DiaryPage/index.jsx
  src/router/Router.jsx
  src/styles/ResetStyle.jsx
Labels: Feature

#153 [feat #140]
  src/assets/lottie/loading.json
  src/components/base/LoadingModal/index.jsx
  src/components/base/Modal/index.jsx
  src/components/base/index.jsx
  src/pages/AlbumCreatePage/index.jsx
Labels: Component

#158 [feat #155] 앨범 메인 페이지 구현
  src/common/api/getAlbumMainDiaries.jsx
  src/components/domain/AlbumMainHeader/index.jsx
  src/components/domain/AlbumMainTimeline/index.jsx
  src/components/domain/index.jsx
  src/pages/AlbumMainPage/index.jsx
  src/pages/MainPage.jsx
  src/pages/index.jsx
  src/router/Router.jsx
Labels: Feature

#169 [feat #161]
  src/common/api/storyBookApi.jsx
  src/components/base/Image/index.jsx
  src/components/domain/StoryBookDiaryList/index.jsx
  src/pages/OAuthRedirect/index.jsx
  src/pages/StoryBookDetailPage/index.jsx
  src/pages/StoryBookPage/index.jsx
  src/pages/TestPage/index.jsx
  src/redux/member/index.jsx
  src/router/PreventedRoute.jsx
  src/router/Router.jsx
Labels: Feature

#165 [feat #157]
  src/common/api/getSpecialMoment.jsx
  src/pages/SpecialMomentPage/index.jsx
Labels: Feature

#166 [feat #164]
  src/common/api/deleteAlbum.jsx
  src/pages/AlbumSettingsPage/index.jsx
Labels: Feature

#171 [feat #170]
  src/components/domain/StoryBookDiaryList/index.jsx
  src/pages/StoryBookDetailPage/index.jsx
  src/pages/StoryBookPage/index.jsx
Labels: Feature

#174 [feat #163] 이미지 슬라이더 데이터 조회 형식 변경
  src/components/domain/AlbumMainTimeline/index.jsx
Labels: Refactoring

#178 [Feat #177] 앨범 메인 페이지 일기 리스트 스타일 수정
  src/components/domain/AlbumMainTimeline/index.jsx
Labels: Refactoring

#193 [feat #191] 일기 상세 페이지 댓글 생성 시 추가된 동적 데이터에 삭제 버튼 UI 적용
  src/components/domain/DiaryComment/index.jsx
  src/pages/DiaryPage/index.jsx
Labels: Feature

#194 [feat #192]
  src/pages/MemberListPage/index.jsx
Labels: Bug

#198 [feat #197]
  src/pages/AlbumSettingsEditPage/index.jsx
Labels: Bug

#203 [feat #202]
  src/pages/AlbumCreatePage/index.jsx
Labels: Refactoring

#205 [feat #204]
  src/styles/ResetStyle.jsx
Labels: Refactoring

#206 v1.0.1 릴리즈 버그 fixed 재배포
  README.md
  public/android-icon-144x144.png
  public/android-icon-192x192.png
  public/android-icon-36x36.png
  public/android-icon-48x48.png
  public/android-icon-72x72.png
  public/android-icon-96x96.png
  public/apple-icon-114x114.png
  public/apple-icon-120x120.png
  public/apple-icon-144x144.png
  public/apple-icon-152x152.png
  public/apple-icon-180x180.png
  public/apple-icon-57x57.png
  public/apple-icon-60x60.png
  public/apple-icon-72x72.png
  public/apple-icon-76x76.png
  public/apple-icon-precomposed.png
  public/apple-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon-96x96.png
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/ms-icon-144x144.png
  public/ms-icon-150x150.png
  public/ms-icon-310x310.png
  public/ms-icon-70x70.png
  src/common/api/deleteDiary.jsx
  src/components/domain/AlbumInviteList/AlbumInviteCard.jsx
  src/components/domain/AlbumMainHeader/index.jsx
  src/components/domain/AlbumMainTimeline/index.jsx
  src/components/domain/DiaryComment/index.jsx
  src/components/domain/DiaryHeaderInfo/index.jsx
  src/pages/AlbumCreatePage/AlbumCreateStep2.jsx
  src/pages/AlbumCreatePage/index.jsx
  src/pages/AlbumMainPage/index.jsx
  src/pages/AlbumSettingsEditPage/index.jsx
  src/pages/AlbumSettingsPage/index.jsx
  src/pages/DiaryPage/index.jsx
  src/pages/MemberInvitePage/index.jsx
  src/pages/MemberListPage/index.jsx
  src/pages/SpecialMomentPage/index.jsx
  src/styles/ResetStyle.jsx
Labels: release

#207 v1.0.1 input style 변경
  src/styles/ResetStyle.jsx
Labels: Refactoring, release

#212 [feat #208]
  src/common/api/memberApi.jsx
  src/components/domain/AlbumInviteList/AlbumInviteCard.jsx
  src/components/domain/ProfileList/index.jsx
  src/redux/member/index.jsx
  src/router/AlbumValidationRoute.jsx
Labels: Feature, Refactoring

#213 [feat #221]
  src/common/api/searchUser.jsx
  src/components/domain/Header/index.jsx
  src/pages/MemberInvitePage/index.jsx
Labels: Bug, Refactoring

#215 [feat #214] 일기 생성 페이지 가상 키보드 활성화에 따른 버튼 UI 수정
  src/components/domain/DiaryCreateStepOne/index.jsx
  src/components/domain/DiaryCreateStepTwo/index.jsx
  src/pages/DiaryCreatePage/index.jsx
Labels: Bug

#218 [feat #217]
  src/pages/ResponseDefaultPage/index.jsx
  src/pages/index.jsx
  src/styles/DefaultTemplate.jsx
Labels: Bug, Feature
